/**
 * Liste exhaustive des devises (ISO 4217).
 * Les devises courantes en transit Maroc sont marquées `pinned: true`.
 */
export type CurrencyEntry = { code: string; name: string; pinned?: boolean };

export const CURRENCIES: CurrencyEntry[] = [
  // Top — devises courantes en transit au Maroc
  { code: "MAD", name: "Dirham marocain", pinned: true },
  { code: "EUR", name: "Euro", pinned: true },
  { code: "USD", name: "Dollar US", pinned: true },
  { code: "GBP", name: "Livre sterling", pinned: true },
  { code: "CNY", name: "Yuan chinois", pinned: true },
  { code: "JPY", name: "Yen japonais", pinned: true },
  { code: "CHF", name: "Franc suisse", pinned: true },
  { code: "AED", name: "Dirham des Émirats", pinned: true },
  { code: "SAR", name: "Riyal saoudien", pinned: true },
  { code: "TRY", name: "Livre turque", pinned: true },

  // Reste — ordre alphabétique
  { code: "AFN", name: "Afghani afghan" },
  { code: "ALL", name: "Lek albanais" },
  { code: "AMD", name: "Dram arménien" },
  { code: "ANG", name: "Florin antillais" },
  { code: "AOA", name: "Kwanza angolais" },
  { code: "ARS", name: "Peso argentin" },
  { code: "AUD", name: "Dollar australien" },
  { code: "AWG", name: "Florin arubais" },
  { code: "AZN", name: "Manat azerbaïdjanais" },
  { code: "BAM", name: "Mark bosnien" },
  { code: "BBD", name: "Dollar barbadien" },
  { code: "BDT", name: "Taka bangladais" },
  { code: "BGN", name: "Lev bulgare" },
  { code: "BHD", name: "Dinar bahreïni" },
  { code: "BIF", name: "Franc burundais" },
  { code: "BMD", name: "Dollar bermudien" },
  { code: "BND", name: "Dollar de Brunei" },
  { code: "BOB", name: "Boliviano" },
  { code: "BRL", name: "Real brésilien" },
  { code: "BSD", name: "Dollar bahaméen" },
  { code: "BTN", name: "Ngultrum bhoutanais" },
  { code: "BWP", name: "Pula du Botswana" },
  { code: "BYN", name: "Rouble biélorusse" },
  { code: "BZD", name: "Dollar bélizien" },
  { code: "CAD", name: "Dollar canadien" },
  { code: "CDF", name: "Franc congolais" },
  { code: "CLP", name: "Peso chilien" },
  { code: "COP", name: "Peso colombien" },
  { code: "CRC", name: "Colón costaricien" },
  { code: "CUP", name: "Peso cubain" },
  { code: "CVE", name: "Escudo cap-verdien" },
  { code: "CZK", name: "Couronne tchèque" },
  { code: "DJF", name: "Franc djiboutien" },
  { code: "DKK", name: "Couronne danoise" },
  { code: "DOP", name: "Peso dominicain" },
  { code: "DZD", name: "Dinar algérien" },
  { code: "EGP", name: "Livre égyptienne" },
  { code: "ERN", name: "Nakfa érythréen" },
  { code: "ETB", name: "Birr éthiopien" },
  { code: "FJD", name: "Dollar fidjien" },
  { code: "FKP", name: "Livre des Malouines" },
  { code: "GEL", name: "Lari géorgien" },
  { code: "GHS", name: "Cedi ghanéen" },
  { code: "GIP", name: "Livre de Gibraltar" },
  { code: "GMD", name: "Dalasi gambien" },
  { code: "GNF", name: "Franc guinéen" },
  { code: "GTQ", name: "Quetzal guatémaltèque" },
  { code: "GYD", name: "Dollar du Guyana" },
  { code: "HKD", name: "Dollar de Hong Kong" },
  { code: "HNL", name: "Lempira hondurien" },
  { code: "HRK", name: "Kuna croate" },
  { code: "HTG", name: "Gourde haïtienne" },
  { code: "HUF", name: "Forint hongrois" },
  { code: "IDR", name: "Roupie indonésienne" },
  { code: "ILS", name: "Shekel israélien" },
  { code: "INR", name: "Roupie indienne" },
  { code: "IQD", name: "Dinar irakien" },
  { code: "IRR", name: "Rial iranien" },
  { code: "ISK", name: "Couronne islandaise" },
  { code: "JMD", name: "Dollar jamaïcain" },
  { code: "JOD", name: "Dinar jordanien" },
  { code: "KES", name: "Shilling kényan" },
  { code: "KGS", name: "Som kirghize" },
  { code: "KHR", name: "Riel cambodgien" },
  { code: "KMF", name: "Franc comorien" },
  { code: "KPW", name: "Won nord-coréen" },
  { code: "KRW", name: "Won sud-coréen" },
  { code: "KWD", name: "Dinar koweïtien" },
  { code: "KYD", name: "Dollar des Caïmans" },
  { code: "KZT", name: "Tenge kazakh" },
  { code: "LAK", name: "Kip laotien" },
  { code: "LBP", name: "Livre libanaise" },
  { code: "LKR", name: "Roupie sri-lankaise" },
  { code: "LRD", name: "Dollar libérien" },
  { code: "LSL", name: "Loti lesothan" },
  { code: "LYD", name: "Dinar libyen" },
  { code: "MDL", name: "Leu moldave" },
  { code: "MGA", name: "Ariary malgache" },
  { code: "MKD", name: "Denar macédonien" },
  { code: "MMK", name: "Kyat birman" },
  { code: "MNT", name: "Tugrik mongol" },
  { code: "MOP", name: "Pataca de Macao" },
  { code: "MRU", name: "Ouguiya mauritanienne" },
  { code: "MUR", name: "Roupie mauricienne" },
  { code: "MVR", name: "Rufiyaa maldivienne" },
  { code: "MWK", name: "Kwacha malawien" },
  { code: "MXN", name: "Peso mexicain" },
  { code: "MYR", name: "Ringgit malaisien" },
  { code: "MZN", name: "Metical mozambicain" },
  { code: "NAD", name: "Dollar namibien" },
  { code: "NGN", name: "Naira nigérian" },
  { code: "NIO", name: "Córdoba nicaraguayen" },
  { code: "NOK", name: "Couronne norvégienne" },
  { code: "NPR", name: "Roupie népalaise" },
  { code: "NZD", name: "Dollar néo-zélandais" },
  { code: "OMR", name: "Rial omanais" },
  { code: "PAB", name: "Balboa panaméen" },
  { code: "PEN", name: "Sol péruvien" },
  { code: "PGK", name: "Kina papouane" },
  { code: "PHP", name: "Peso philippin" },
  { code: "PKR", name: "Roupie pakistanaise" },
  { code: "PLN", name: "Zloty polonais" },
  { code: "PYG", name: "Guarani paraguayen" },
  { code: "QAR", name: "Riyal qatari" },
  { code: "RON", name: "Leu roumain" },
  { code: "RSD", name: "Dinar serbe" },
  { code: "RUB", name: "Rouble russe" },
  { code: "RWF", name: "Franc rwandais" },
  { code: "SBD", name: "Dollar des Salomon" },
  { code: "SCR", name: "Roupie seychelloise" },
  { code: "SDG", name: "Livre soudanaise" },
  { code: "SEK", name: "Couronne suédoise" },
  { code: "SGD", name: "Dollar de Singapour" },
  { code: "SHP", name: "Livre de Sainte-Hélène" },
  { code: "SLL", name: "Leone sierra-léonais" },
  { code: "SOS", name: "Shilling somalien" },
  { code: "SRD", name: "Dollar surinamais" },
  { code: "SSP", name: "Livre sud-soudanaise" },
  { code: "STN", name: "Dobra santoméen" },
  { code: "SYP", name: "Livre syrienne" },
  { code: "SZL", name: "Lilangeni swazi" },
  { code: "THB", name: "Baht thaïlandais" },
  { code: "TJS", name: "Somoni tadjik" },
  { code: "TMT", name: "Manat turkmène" },
  { code: "TND", name: "Dinar tunisien" },
  { code: "TOP", name: "Paʻanga tongien" },
  { code: "TTD", name: "Dollar de Trinité-et-Tobago" },
  { code: "TWD", name: "Dollar taïwanais" },
  { code: "TZS", name: "Shilling tanzanien" },
  { code: "UAH", name: "Hryvnia ukrainienne" },
  { code: "UGX", name: "Shilling ougandais" },
  { code: "UYU", name: "Peso uruguayen" },
  { code: "UZS", name: "Som ouzbek" },
  { code: "VES", name: "Bolivar vénézuélien" },
  { code: "VND", name: "Dong vietnamien" },
  { code: "VUV", name: "Vatu vanuatuan" },
  { code: "WST", name: "Tala samoan" },
  { code: "XAF", name: "Franc CFA (BEAC)" },
  { code: "XCD", name: "Dollar des Caraïbes" },
  { code: "XOF", name: "Franc CFA (BCEAO)" },
  { code: "XPF", name: "Franc CFP" },
  { code: "YER", name: "Rial yéménite" },
  { code: "ZAR", name: "Rand sud-africain" },
  { code: "ZMW", name: "Kwacha zambien" },
  { code: "ZWL", name: "Dollar zimbabwéen" },
];
